server:
  port: 5555

spring:
  datasource:
    url: jdbc:h2:mem:taskmanagerdb
    driver-class-name: org.h2.Driver
    username: ${H2_DB_USERNAME}
    password: ${H2_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true